### ISSUE TITLE
generate-codecamp concept & updates

### ISSUE THREAD

**Issue by serapath** [playproject-io/generate-codecamp#1]
## `@todo`
* [ ] make first draft for code camp landing page
* [ ] add all workshops to codecamp page
* [ ] publish play landingpage as static basic, but functional curriculum (links to workshops) page
* [ ] brush codecamp design to look awesome :-D

---
